export const ON_FETCH_BEGIN = 'ON_FETCH_BEGIN';
<<<<<<< HEAD
export const ON_USERDATA_FETCH_SUCCESS = 'ON_USERDATA_FETCH_SUCCESS';
export const ON_USERDATA_FETCH_ERROR = 'ON_USERDATA_FETCH_ERROR';
=======
export const ON_EDUCATION_FETCH_SUCCESS = 'ON_EDUCATION_FETCH_SUCCESS';
export const ON_EDUCATION_FETCH_ERROR = 'ON_EDUCATION_FETCH_ERROR';
>>>>>>> 1ae6ba18804ecdfae7a7a41fa63ef3aebcd1d0b3
export const SIGN_OUT = 'SIGN_OUT';
export const SESSION_EXPIRED = 'SESSION_EXPIRED';
export const ON_UPDATE_SUCCESS = 'ON_UPDATE_SUCCESS';
export const ON_UPDATE_ERROR = 'ON_UPDATE_ERROR';
